language: node_js
node_js:
  - 14.17
cache:
  directories:
    - node_modules
script:
  - npm run test:coveralls
  - npm run build
deploy:
  provider: surge
  project: ./static/
  domain: itaylorcodes-neighborhoodz.surge.sh
  on:
    branch: main
