language: node_js
node_js:
  - 14.17
cache:
  directories:
    - node_modules
script:
  - npm run test:coveralls
  - npm run build
deploy:
  provider: surge
  domain: itaylorcodes-neighborhoodz.surge.sh
  project: ./build/index.html
  on:
    branch: main
